
import { StyleSheet } from 'react-native';
import { colors } from '../../../../Colors/colors';

const styles = StyleSheet.create({
    container:{
        backgroundColor:'#fff',
        flexGrow:1
    },
    addTournament:{
        backgroundColor:'#fff'
    },
    addBtn:{
        padding:15,
        alignItems:'center',
        borderBottomColor:'#dff9fb',
        borderBottomWidth:0.5,
        marginBottom:12
    },
    addFont:{
        color:colors.primaryColor,
        fontFamily:'OpenSans-SemiBold',
        marginTop:5
    },
    gameBtn:{
        borderRadius:12,
        marginHorizontal:20,
        marginVertical:6,
        padding:50,
        backgroundColor:'#fff',
        borderColor:'#dcdde1',
        borderWidth:0.6,
        alignItems:'center'
    },
    gameBtntext:{
        color:colors.primaryColor,
        fontFamily:'OpenSans-Bold',
        fontSize:18
    },
    levelText:{
        letterSpacing:2,
        color:'#CCCCCC',
        fontSize:16,
        marginTop:10
    },
    pending:{
        color:'#ff3838',
        fontFamily:'OpenSans-SemiBold',
        marginTop:10
    },
    ongoing:{
        color:'#32ff7e',
        fontFamily:'OpenSans-SemiBold',
        marginTop:10
    },
    header:{
        backgroundColor:'#fff',
        padding:30,
        alignItems:'center',
        justifyContent:'center'
    },
    headerText:{
        color:colors.primaryColor,
        fontFamily:'OpenSans-SemiBold',
        fontSize:16
    },
    scoreBoard:{
        padding:10,
        backgroundColor:'#1e3799',
        borderRadius:100,
        marginHorizontal:25,
        flexDirection:'row'
    },
    teamName:{
        color:'#fff',
        fontSize:18,
        fontFamily:'OpenSans-SemiBold',
        margin:20
    },
    nameCntnr:{
        flexDirection:'row',
        alignItems:'center'
    },
    gmeMsg:{
        alignSelf:'center',
        margin:10,
        fontFamily:'OpenSans-SemiBold',
        color:colors.primaryColor,
        fontSize:12
    },
    scoreCalc:{
        flexDirection:'row',
        marginTop:20,
        flex:1,
        borderTopWidth:0.9,
        borderColor:'grey',
        justifyContent:'center'
    },
    score:{
        height:50,
        width:50,
        margin:10
    }
})

export default styles;